<!-- START of: finna - feedback/dynamic-form.phtml -->
<?
  $form = $this->form;
  $form->prepare();

  $title = $form->getTitle();
  $title = !empty($title) && !$this->translationEmpty($title)
    ? $this->translate($title) : null;

  $formUrl = $this->url('feedback-form', ['id' => $this->formId]);
  $form->setAttribute('action', $formUrl);
  $form->setAttribute('class', 'dynamic-form');
  $form->setAttribute('method', 'post');

  $help = $form->getHelp();
?>
<div class="feedback-content">
  <? if ($title): ?>
    <? $this->headTitle($title); $this->content()->setHeading($title); ?>
  <? endif; ?>
  <?=$this->flashmessages()?>

  <? if ($form->showOnlyForLoggedUsers() && !$this->user): ?>
     <div class="form-group">
        <p><?=$this->translate('feedback_login_required')?></p>
        <a href="<?=$this->url('myresearch-userlogin')?>" class="btn btn-primary btn-uppercase" data-lightbox data-lightbox-onclose="window.location.href='<?=$this->escapeHtmlAttr($formUrl) ?>'"><i class="fa fa-sign-in fa-lg" aria-hidden="true"></i><span class="login-text"><?=$this->transEsc("Login")?></span></a>
    </div>  
  <? else: ?>
    <?= $this->form()->openTag($form); ?>
    <? if (!empty($help['pre'])): ?>
    <div class="form-group">
      <div class="form-info pre">
        <?=$this->translate($help['pre'], ['%%institution%%' => $this->institutionName]);?>
      </div>
    </div>
    <? endif ?>

    <? $currentGroup = null; ?>
    <? foreach($form->getElements() as $el): ?>
      <?
      $formElement = $form->get($el['name']);

      // Group form elements into field sets
      $handleGroup = $group = null;
      if (isset($el['group']) && !empty($el['group'])) {
          $group = $el['group'];
      }
      if ($group && $currentGroup === null) {
          $handleGroup = 'open';
          $currentGroup = $group;
      } else if ($currentGroup && !$group) {
          $handleGroup = 'close';
          $currentGroup = null;
      } else if ($currentGroup !== $group) {
          $handleGroup = 'openAndClose';
          $currentGroup = $group;
      }
      ?>

    <? if (in_array($handleGroup, ['close', 'openAndClose'])): ?>
      </div>
    <? endif ?>
    <? if (in_array($handleGroup, ['open', 'openAndClose'])): ?>
      <div class="field-set">
    <? endif ?>

    <div class="form-group">
    <? if (!empty($el['help'])): ?>
      <p class="info"><?= $this->transEsc($el['help']) ?></p>
    <? endif ?>
    <? if ($el['type'] !== 'submit'): ?>
      <label for="<?=$this->escapeHtmlAttr($el['name'])?>" class="control-label<?=!empty($el['required']) ? ' required' : ''?>"><?=$this->transEsc($el['label'])?>:</label>
    <? else: ?>
      <? if (!empty($help['post'])): ?>
        <div class="form-info post">
          <?=$this->translate($help['post'], ['%%institution%%' => $this->institutionName]);?>
        </div>
      <? endif ?>
    <? endif ?>
    <?= $this->formRow($formElement) ?>
    </div>
  <? endforeach ?>
  <?= $this->form()->closeTag() ?>
  <? endif ?>
</div>
<?
  if ($title) {
     $this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
         'content/header.phtml',
         [
           'heading' => $this->content()->getHeading(),
         ]
     );
  }
?>
<!-- END of: finna - feedback/dynamic-form.phtml -->
