<!-- START of: finna - feedback/error.phtml -->
<?php
  $title = $this->transEsc($this->form->getTitle() ?? '');
?>
<?php if (!$this->inLightbox): ?>
  <div class="feedback-content">
<?php endif; ?>
<?php if ($title): ?>
    <?php $this->headTitle($title); ?>
    <?php $headTag = $this->inLightbox ? 'h2' : 'h1'; ?>
    <<?=$headTag?>><?=$title?></<?=$headTag?>>
<?php endif; ?>
<?=$this->flashmessages()?>
<?php if (!$this->inLightbox): ?>
  </div>
<?php endif; ?>
<!-- END of: finna - feedback/error.phtml -->
