<!-- START of: finna - myresearch/profile-nickname.phtml -->
<?php if ($user): ?>
    <div>
        <span class="myresearch-profile-middle-header"><?= $this->transEsc('finna_nickname') ?></span>
    </div>
    <form name="nickname_form" class="inline" method="post">
      <div class="my-profile-row">
        <div class="my-profile-col">
          <label for="finna_nickname"><?=$this->transEsc("finna_nickname") ?>:</label>
        </div>
        <div class="my-profile-col">
          <input id="finna_nickname" type="text" class="form-control profileinfo-fields" name="finna_nickname" value="<?=$this->escapeHtml(trim($this->userPublicName($user)))?>" pattern="^(?!.*[._]{2})[A-ZÅÄÖa-zåäö0-9._]{3,24}$" title="<?=$this->transEsc('finna_nickname_restrictions')?>"/>
        </div>
        <div class="clearfix visible-xs"></div>
        <div class="my-profile-col">
          <i class="fa fa-info-circle-hollow"></i><?=$this->transEsc("finna_nickname_info")?>
        </div>
      </div>
      <div class="my-profile-row">
          <input id="save-user-profile" name="saveUserNickname" type="submit" value="<?=$this->transEsc("Save") ?>" class="btn btn-primary" />
      </div>
    </form>
<?php endif; ?>
<!-- END of: finna - myresearch/profile-my-information.phtml -->
