<!-- START of: finna - primo/home-1_fi.phtml -->
<div class="row">
  <div class="col-sm-5">
    <div class="infobox">
      <p>Kansalliskirjasto on digitoitunut kaikki Suomessa vuosina 1771-1910 ilmestyneet sanomalehdet, ja ne ovat vapaasti käytössä tämän palvelun kautta. Muutamat tätä uudemmat digitoidut sanomalehdet ovat käytettävissä kaikissa <a href="https://www.kiwi.fi/display/Vapaakappalepalvelut/Palvelun+kuvaus+ja+ohjeet#Palvelunkuvausjaohjeet-Vapaakappalekirjastot">vapaakappalekirjastoissa</a>.</p>
    </div>
  </div>
  <div class="col-sm-7">
    <p>&nbsp;</p>
    <p>Tutustu Suomen historiaan ja menneeseen aikaan digitoitujen sanomalehtien kautta!</p>
  </div>
</div>
<!-- END of: finna - primo/home-1_fi.phtml -->
