<!-- START of: finna - digi/home.phtml -->
<?
  // Set page title.
  $this->headTitle($this->translate('Digi Search'));
  $this->layout()->finnaMainHeader = '<div class="col-xs-12"><h1 class="content-header">'.$this->translate('Digi Search').'</h1></div>';
  // Disable top search box -- this page has a special layout.

  // Load search actions and settings (if any):
  $options = $this->searchOptions('digi');
  $basicSearch = $options->getSearchAction();

  $this->layout()->breadcrumbs = false;
  $this->layout()->logosection = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>
<!--  Begin home.phtml and close page container for extra styling  -->
</div>
<div class="container-fluid digi-home">
  <div class="container">
    <div class="row">
       <div class="col-xs-12">
          <? if ($template = $this->content()->findTemplateForLng('digi/home-1')): ?>
          <?=$this->render($template)?>
          <? endif; ?>
        </div>
    </div>
  </div>
</div>
<!-- reopen container -->
<div class="container">
<!-- END of: finna - digi/home.phtml -->
