<!-- START of: finna - myresearch/profile-my-information.phtml -->
<? if ($user): ?>
<div>
  <div class="myresearch-profile-list">
    <div>
      <h2><?=$this->transEsc('my_profile')?></h2>
    </div>
    <form name="my_profile_form" class="inline" method="post">
      <? if (!$this->hideProfileEmailAddress): ?>
          <div class="my-profile-col">
            <label for="email"><?=$this->transEsc("Email") ?>:</label>
          </div>
          <div class="my-profile-col">
            <input id="email" type="email" class="form-control" name="email" value="<?=$user->email?>"/>
          </div>
          <div class="clearfix visible-xs"></div>
          <div class="my-profile-col">
            <i class="fa fa-info-big"></i>  <?=$this->transEsc("email_info") ?>
          </div>
          <div class="clearfix visible-xs"><br/></div>
          <div class="my-profile-col">
            <label for="finna_nickname"><?=$this->transEsc("finna_nickname") ?>:</label>
          </div>
          <div class="my-profile-col">
            <input id="finna_nickname" type="text" class="form-control" name="finna_nickname" value="<?=$this->escapeHtml(trim($this->userPublicName($user)))?>" required pattern ="^(?!.*[_.]{2})[A-ZÅÄÖa-zåäö0-9_.]{3,24}$" title="<?=$this->transEsc("finna_nickname_restrictions") ?>"/>
          </div>
          <div class="clearfix visible-xs"></div>
          <div class="my-profile-col">
            <i class="fa fa-info-big"></i>  <?=$this->transEsc("finna_nickname_info") ?><br/>
          </div>
          <div class="clearfix visible-xs"><br/></div>
            <input id="save-user-profile" name="saveUserProfile" type="submit" value="<?=$this->transEsc("Save") ?>" class="btn btn-primary" />
      <? endif; ?>
    </form>
  </div>
  <div class="myresearch-profile-list">
    <? if ($this->auth()->isLoggedIn() && !in_array($this->auth()->getManager()->getAuthClassForTemplateRendering(), ['Finna\Auth\ILS', 'Finna\Auth\MultiILS']) && $this->auth()->getManager()->supportsPasswordChange()): ?>
      <a href="<?=$this->url('myresearch-changepassword') ?>" class="btn btn-primary" data-lightbox><?=$this->transEsc('Change Password') ?></a>
    <? endif; ?>
  </div>
</div>
<? endif; ?>
<!-- END of: finna - myresearch/profile-my-information.phtml -->
