<!-- START of: finna - record/feedback.phtml -->
<?
  $user = $this->auth()->isLoggedIn();
?>
<h2><?= $this->transEsc('Send feedback on record'); ?></h2>

<? if (!$this->translationEmpty('record_feedback_instructions')): ?>
  <p><?=$this->transEsc("record_feedback_instructions"); ?></p>
<? endif; ?>

  <?=$this->flashmessages()?>
    <form class="form feedback-form" method="post" name="feedbackRecord" action="<?= $this->recordLink()->getActionUrl($this->driver, 'Feedback') ?>">
    <div class="row">
      <input type="hidden" name="id" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" />
      <div class="form-group col-xs-12">
        <div class="feedback-info">
          <label for="feedback_from" class="control-label">
            <?= $this->TransEsc('Send feedback on record'); ?>: <?=$this->escapeHtml($this->organisationDisplayName($this->driver, true)) ?>
          </label>
        </div>
      </div>
    </div>
    <?= $this->dynamicForm('FeedbackRecord', ['elementsOnly' => true]) ?>

    <div class="form-group">
        <div>
            <input class="btn btn-primary" type="submit" name="submitFeedback" value="<?= $this->TransEsc('Send'); ?>"/>
        </div>
      </div>
    </div>
  </form>
<!-- END of: finna - record/feedback.phtml -->
