<?php
$locations = $this->driver->getLocations();
$links = ['https://finna.fi', 'https://finna.fi', 'https://finna.fi'];
?>

<div class="table record-locationsead3-links">
  <div class="headers">
    <p class="holdings-title">Linkit</p>
  </div>
  <?php foreach ($links as $link): ?>
    <div class="copy-details">
      <span class="branch"><a href="<?=$this->escapeHtmlAttr($link)?>"><i class="fa fa-external-link" aria-hidden="true"></i> <?=$link?></a></span>
    </div>
  <?php endforeach; ?>
</div>

<div class="table record-locationsead3-table">
  <div class="headers"><p class="holdings-title">Säilyttävät toimipisteet</p></div>

  <?php foreach ($locations as $branch => $branchData): ?>
  <div class="holdings-container-heading">
      <div class="location">
          <i class="fa fa-arrow-down" aria-hidden="true"></i> <?=$branch?></div>
          <div class="holdings-details">Aineistotunnus</div>
          <div class="location-link text-right">
              <div class="location-link-text">Tarjoaa tietopalvelua</div>
          </div>
  </div>
  <div class="clearfix collapsed"></div>
  <?php foreach ($branchData['items'] as $item): ?>
  <div vocab="http://schema.org/" typeof="Offer" class="copy-details">
      <div class="copy-title">
          <span class="branch"><?=$this->transEsc($item['label'])?>
      </div>
      <div class="copy-info">
          <span><?=$this->transEsc($item['id'])?></span>
          <div class="pull-right">
          </div>
          <div class="copy-available">
              <div class="available">Tarjoaa tietopalvelua</div>
          </div>
      </div>
  </div>
  <?php endforeach; ?>
  <?php endforeach; ?>
</div>

<?php
  $this->inlineScript(
    \Zend\View\Helper\HeadScript::SCRIPT,
    'finna.record.setupLocationsEad3Tab();',
    'SET'
  );
  echo $this->inlineScript();
?>
