<!-- START of: finna - ajax/authority.phtml -->
<?
  $formatter = $this->recordDataFormatter();
  $coreFields = $formatter->getData(
     $driver, $formatter->filterAuthorityFields($formatter->getDefaults('authority'))
  );
?>

<? $description = $driver->getDescription(); ?>
<? if (!empty($description)): ?>
<div class="description"><?= $description ?></div>
<? endif; ?>

<? if (!empty($coreFields)): ?>
<table class="table table-finna-record record-details">
  <? foreach ($coreFields as $key => $current): ?>
  <tr class="<?=$current['context']['class'];?>"><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>

<? // NOTE: fullrecord outputted for debugging purposes.
<? $rawFieldData = $this->driver->getRawData(); ?>
<? if (!empty($rawFieldData['fullrecord']) && strncmp($rawFieldData['fullrecord'], '<', 1) == 0): ?>
<pre id="record-data" style="display: none;">
<?
  $dom = new DOMDocument('1.0');
  $dom->preserveWhiteSpace = false;
  $dom->formatOutput = true;
  if ($dom->loadXML($rawFieldData['fullrecord'])) {
    echo $this->escapeHtml($dom->saveXML());
    $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/highlight.pack.js');
    echo $this->inlineScript();
    $script = <<<JS
$(document).ready(function() {
  $('#record-data').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
JS;
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
  } else {
    echo $this->escapeHtml($rawFieldData['fullrecord']);
  }
?>
<? endif ?>
</pre>
<!-- END of: finna - ajax/authority.phtml -->
