<? //Don't add START and END comments ?>
<?
  $url = $this->record($this->driver)->getLink('author', $data);
  $authority = $this->driver->getOriginationExtended()
?>
<? if ($authority && ($authorityLink = $this->authority()->link($url, $data, $authority['id'], $authority['type'], $this->driver->getDatasource()))): ?>
  <?=$authorityLink?>
  <?=$this->authority()->recordInfo()?>
  <p>daa</p>
<? else: ?>
  <a href="<?=$url?>"><?=$this->escapeHtml($data)?></a>
<? endif; ?>
