<? if (!empty($this->authority)): ?>
<a href="<?=$this->link?>"<?= $authority ? (' data-authority="' . $this->authority['id'] . '" data-source="' . $this->recordSource . '" data-type="' . $this->authority['type'] . '" class="authority" ') : ''?>><?=$this->escapeHtml($this->label)?><? if ($authority): ?> <i class="show-info fa fa-arrow-down"></i><i class="hide-info fa fa-arrow-up"></i><? endif ?></a>
<? else: ?>
<a href="<?=$this->link?>"><?=$this->escapeHtml($this->label)?></a>
<? endif; ?>